global using ImGuiNET;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using TerraAngel;
global using TerraAngel.Cheat;
global using TerraAngel.Cheat.Cringes;
global using TerraAngel.UI;
global using TerraAngel.UI.ClientWindows;
global using TerraAngel.Config;
global using TerraAngel.Graphics;
global using TerraAngel.Hooks;
global using TerraAngel.Input;
global using TerraAngel.Utility;
global using TerraAngel.Timing;
global using TerraAngel.Vectors;
global using TerraAngel.Assets;
global using Terraria;
global using Terraria.ID;
global using NRectangle = System.Drawing.Rectangle;
global using Rectangle = Microsoft.Xna.Framework.Rectangle;
global using System.Numerics;
global using Matrix = System.Numerics.Matrix4x4;